BEGIN

  -- Khoa Phong
  INSERT INTO DMKHOAPHONGBV (TENKHOAPHONG) VALUES ('Khoa Phong 1');
  INSERT INTO DMKHOAPHONGBV (TENKHOAPHONG) VALUES ('Khoa Phong 2');
  INSERT INTO DMKHOAPHONGBV (TENKHOAPHONG) VALUES ('Khoa Phong 3');
  INSERT INTO DMKHOAPHONGBV (TENKHOAPHONG) VALUES ('Khoa Phong 4');
  INSERT INTO DMKHOAPHONGBV (TENKHOAPHONG) VALUES ('Khoa Phong 5');

  -- Benh Nhan, Vien Phi
  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 1', 'Nu', 'Dia chi 1', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 16, TRUNC(SYSDATE) - 14, TRUNC(SYSDATE) - 14, 448000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 448000, 448000, TRUNC(SYSDATE) - 14);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 2', 'Nam', 'Dia chi 2', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 8, TRUNC(SYSDATE) - 8, 175000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 175000, 175000, TRUNC(SYSDATE) - 8);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 3', 'Nu', 'Dia chi 3', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 26, TRUNC(SYSDATE) - 24, TRUNC(SYSDATE) - 24, 226000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 226000, 226000, TRUNC(SYSDATE) - 24);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 4', 'Nu', 'Dia chi 4', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 3, TRUNC(SYSDATE) - 1, TRUNC(SYSDATE) - 1, 174000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 174000, 174000, TRUNC(SYSDATE) - 1);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 5', 'Nam', 'Dia chi 5', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 19, TRUNC(SYSDATE) - 17, TRUNC(SYSDATE) - 17, 461000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 461000, 461000, TRUNC(SYSDATE) - 17);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 6', 'Nu', 'Dia chi 6', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 27, TRUNC(SYSDATE) - 25, TRUNC(SYSDATE) - 25, 132000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 132000, 132000, TRUNC(SYSDATE) - 25);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 7', 'Nam', 'Dia chi 7', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 4, TRUNC(SYSDATE) - 2, TRUNC(SYSDATE) - 2, 459000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 459000, 459000, TRUNC(SYSDATE) - 2);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 8', 'Nam', 'Dia chi 8', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 31, TRUNC(SYSDATE) - 29, TRUNC(SYSDATE) - 29, 247000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 247000, 247000, TRUNC(SYSDATE) - 29);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 9', 'Nu', 'Dia chi 9', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 29, TRUNC(SYSDATE) - 27, TRUNC(SYSDATE) - 27, 148000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 148000, 148000, TRUNC(SYSDATE) - 27);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 10', 'Nam', 'Dia chi 10', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 4, TRUNC(SYSDATE) - 2, TRUNC(SYSDATE) - 2, 149000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 149000, 149000, TRUNC(SYSDATE) - 2);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 11', 'Nu', 'Dia chi 11', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 7, TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 5, 381000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 381000, 381000, TRUNC(SYSDATE) - 5);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 12', 'Nu', 'Dia chi 12', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 18, 268000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 268000, 268000, TRUNC(SYSDATE) - 18);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 13', 'Nu', 'Dia chi 13', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 29, TRUNC(SYSDATE) - 27, TRUNC(SYSDATE) - 27, 291000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 291000, 291000, TRUNC(SYSDATE) - 27);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 14', 'Nam', 'Dia chi 14', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 12, TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 10, 252000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 252000, 252000, TRUNC(SYSDATE) - 10);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 15', 'Nu', 'Dia chi 15', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 6, TRUNC(SYSDATE) - 4, TRUNC(SYSDATE) - 4, 434000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 434000, 434000, TRUNC(SYSDATE) - 4);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 16', 'Nam', 'Dia chi 16', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 2, TRUNC(SYSDATE) - 0, TRUNC(SYSDATE) - 0, 132000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 132000, 132000, TRUNC(SYSDATE) - 0);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 17', 'Nu', 'Dia chi 17', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 2, TRUNC(SYSDATE) - 0, TRUNC(SYSDATE) - 0, 172000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 172000, 172000, TRUNC(SYSDATE) - 0);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 18', 'Nam', 'Dia chi 18', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 16, TRUNC(SYSDATE) - 16, 141000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 141000, 141000, TRUNC(SYSDATE) - 16);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 19', 'Nu', 'Dia chi 19', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 32, TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 30, 290000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 290000, 290000, TRUNC(SYSDATE) - 30);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 20', 'Nam', 'Dia chi 20', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 21, TRUNC(SYSDATE) - 21, 399000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 399000, 399000, TRUNC(SYSDATE) - 21);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 21', 'Nu', 'Dia chi 21', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 28, TRUNC(SYSDATE) - 26, TRUNC(SYSDATE) - 26, 302000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 302000, 302000, TRUNC(SYSDATE) - 26);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 22', 'Nam', 'Dia chi 22', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 9, TRUNC(SYSDATE) - 7, TRUNC(SYSDATE) - 7, 412000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 412000, 412000, TRUNC(SYSDATE) - 7);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 23', 'Nu', 'Dia chi 23', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 26, TRUNC(SYSDATE) - 24, TRUNC(SYSDATE) - 24, 354000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 354000, 354000, TRUNC(SYSDATE) - 24);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 24', 'Nu', 'Dia chi 24', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 18, 371000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 371000, 371000, TRUNC(SYSDATE) - 18);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 25', 'Nu', 'Dia chi 25', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 8, TRUNC(SYSDATE) - 8, 292000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 292000, 292000, TRUNC(SYSDATE) - 8);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 26', 'Nu', 'Dia chi 26', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 15, TRUNC(SYSDATE) - 13, TRUNC(SYSDATE) - 13, 474000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 474000, 474000, TRUNC(SYSDATE) - 13);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 27', 'Nam', 'Dia chi 27', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 3, TRUNC(SYSDATE) - 3, 491000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 491000, 491000, TRUNC(SYSDATE) - 3);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 28', 'Nu', 'Dia chi 28', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 25, TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 23, 242000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 242000, 242000, TRUNC(SYSDATE) - 23);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 29', 'Nam', 'Dia chi 29', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 15, TRUNC(SYSDATE) - 13, TRUNC(SYSDATE) - 13, 131000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 131000, 131000, TRUNC(SYSDATE) - 13);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 30', 'Nam', 'Dia chi 30', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 25, TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 23, 172000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 172000, 172000, TRUNC(SYSDATE) - 23);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 31', 'Nu', 'Dia chi 31', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 27, TRUNC(SYSDATE) - 25, TRUNC(SYSDATE) - 25, 263000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 263000, 263000, TRUNC(SYSDATE) - 25);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 32', 'Nu', 'Dia chi 32', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 7, TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 5, 110000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 110000, 110000, TRUNC(SYSDATE) - 5);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 33', 'Nu', 'Dia chi 33', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 8, TRUNC(SYSDATE) - 6, TRUNC(SYSDATE) - 6, 435000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 435000, 435000, TRUNC(SYSDATE) - 6);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 34', 'Nam', 'Dia chi 34', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 28, TRUNC(SYSDATE) - 26, TRUNC(SYSDATE) - 26, 250000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 250000, 250000, TRUNC(SYSDATE) - 26);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 35', 'Nam', 'Dia chi 35', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 28, TRUNC(SYSDATE) - 28, 166000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 166000, 166000, TRUNC(SYSDATE) - 28);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 36', 'Nu', 'Dia chi 36', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 25, TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 23, 233000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 233000, 233000, TRUNC(SYSDATE) - 23);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 37', 'Nam', 'Dia chi 37', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 18, 349000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 349000, 349000, TRUNC(SYSDATE) - 18);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 38', 'Nu', 'Dia chi 38', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 16, TRUNC(SYSDATE) - 14, TRUNC(SYSDATE) - 14, 176000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 176000, 176000, TRUNC(SYSDATE) - 14);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 39', 'Nam', 'Dia chi 39', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 31, TRUNC(SYSDATE) - 29, TRUNC(SYSDATE) - 29, 300000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 300000, 300000, TRUNC(SYSDATE) - 29);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 40', 'Nam', 'Dia chi 40', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 2, TRUNC(SYSDATE) - 0, TRUNC(SYSDATE) - 0, 275000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 275000, 275000, TRUNC(SYSDATE) - 0);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 41', 'Nam', 'Dia chi 41', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 25, TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 23, 332000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 332000, 332000, TRUNC(SYSDATE) - 23);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 42', 'Nam', 'Dia chi 42', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 3, TRUNC(SYSDATE) - 3, 349000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 349000, 349000, TRUNC(SYSDATE) - 3);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 43', 'Nam', 'Dia chi 43', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 8, TRUNC(SYSDATE) - 8, 358000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 358000, 358000, TRUNC(SYSDATE) - 8);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 44', 'Nam', 'Dia chi 44', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 8, TRUNC(SYSDATE) - 8, 301000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 301000, 301000, TRUNC(SYSDATE) - 8);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 45', 'Nu', 'Dia chi 45', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 26, TRUNC(SYSDATE) - 24, TRUNC(SYSDATE) - 24, 270000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 270000, 270000, TRUNC(SYSDATE) - 24);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 46', 'Nam', 'Dia chi 46', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 6, TRUNC(SYSDATE) - 4, TRUNC(SYSDATE) - 4, 437000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 437000, 437000, TRUNC(SYSDATE) - 4);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 47', 'Nam', 'Dia chi 47', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 28, TRUNC(SYSDATE) - 28, 165000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 165000, 165000, TRUNC(SYSDATE) - 28);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 48', 'Nu', 'Dia chi 48', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 31, TRUNC(SYSDATE) - 29, TRUNC(SYSDATE) - 29, 165000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 165000, 165000, TRUNC(SYSDATE) - 29);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 49', 'Nu', 'Dia chi 49', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 19, TRUNC(SYSDATE) - 17, TRUNC(SYSDATE) - 17, 129000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 129000, 129000, TRUNC(SYSDATE) - 17);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 50', 'Nam', 'Dia chi 50', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 18, 262000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 262000, 262000, TRUNC(SYSDATE) - 18);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 51', 'Nu', 'Dia chi 51', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 21, TRUNC(SYSDATE) - 19, TRUNC(SYSDATE) - 19, 137000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 137000, 137000, TRUNC(SYSDATE) - 19);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 52', 'Nu', 'Dia chi 52', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 12, TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 10, 168000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 168000, 168000, TRUNC(SYSDATE) - 10);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 53', 'Nam', 'Dia chi 53', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 16, TRUNC(SYSDATE) - 14, TRUNC(SYSDATE) - 14, 470000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 470000, 470000, TRUNC(SYSDATE) - 14);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 54', 'Nam', 'Dia chi 54', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 3, TRUNC(SYSDATE) - 3, 259000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 259000, 259000, TRUNC(SYSDATE) - 3);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 55', 'Nu', 'Dia chi 55', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 12, TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 10, 217000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 217000, 217000, TRUNC(SYSDATE) - 10);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 56', 'Nam', 'Dia chi 56', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 31, TRUNC(SYSDATE) - 29, TRUNC(SYSDATE) - 29, 246000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 246000, 246000, TRUNC(SYSDATE) - 29);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 57', 'Nam', 'Dia chi 57', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 12, TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 10, 318000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 318000, 318000, TRUNC(SYSDATE) - 10);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 58', 'Nam', 'Dia chi 58', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 21, TRUNC(SYSDATE) - 19, TRUNC(SYSDATE) - 19, 359000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 359000, 359000, TRUNC(SYSDATE) - 19);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 59', 'Nu', 'Dia chi 59', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 24, TRUNC(SYSDATE) - 22, TRUNC(SYSDATE) - 22, 443000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 443000, 443000, TRUNC(SYSDATE) - 22);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 60', 'Nam', 'Dia chi 60', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 21, TRUNC(SYSDATE) - 21, 207000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 207000, 207000, TRUNC(SYSDATE) - 21);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 61', 'Nam', 'Dia chi 61', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 32, TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 30, 378000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 378000, 378000, TRUNC(SYSDATE) - 30);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 62', 'Nu', 'Dia chi 62', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 16, TRUNC(SYSDATE) - 14, TRUNC(SYSDATE) - 14, 180000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 180000, 180000, TRUNC(SYSDATE) - 14);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 63', 'Nu', 'Dia chi 63', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 7, TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 5, 272000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 272000, 272000, TRUNC(SYSDATE) - 5);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 64', 'Nam', 'Dia chi 64', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 28, TRUNC(SYSDATE) - 28, 434000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 434000, 434000, TRUNC(SYSDATE) - 28);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 65', 'Nam', 'Dia chi 65', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 16, TRUNC(SYSDATE) - 14, TRUNC(SYSDATE) - 14, 123000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 123000, 123000, TRUNC(SYSDATE) - 14);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 66', 'Nam', 'Dia chi 66', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 28, TRUNC(SYSDATE) - 28, 425000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 425000, 425000, TRUNC(SYSDATE) - 28);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 67', 'Nam', 'Dia chi 67', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 7, TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 5, 181000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 181000, 181000, TRUNC(SYSDATE) - 5);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 68', 'Nam', 'Dia chi 68', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 7, TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 5, 354000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 354000, 354000, TRUNC(SYSDATE) - 5);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 69', 'Nu', 'Dia chi 69', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 4, TRUNC(SYSDATE) - 2, TRUNC(SYSDATE) - 2, 428000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 428000, 428000, TRUNC(SYSDATE) - 2);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 70', 'Nu', 'Dia chi 70', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 12, TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 10, 427000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 427000, 427000, TRUNC(SYSDATE) - 10);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 71', 'Nu', 'Dia chi 71', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 18, 468000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 468000, 468000, TRUNC(SYSDATE) - 18);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 72', 'Nam', 'Dia chi 72', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 21, TRUNC(SYSDATE) - 21, 171000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 171000, 171000, TRUNC(SYSDATE) - 21);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 73', 'Nam', 'Dia chi 73', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 17, TRUNC(SYSDATE) - 15, TRUNC(SYSDATE) - 15, 395000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 395000, 395000, TRUNC(SYSDATE) - 15);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 74', 'Nam', 'Dia chi 74', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 7, TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 5, 303000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 303000, 303000, TRUNC(SYSDATE) - 5);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 75', 'Nam', 'Dia chi 75', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 19, TRUNC(SYSDATE) - 17, TRUNC(SYSDATE) - 17, 325000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 325000, 325000, TRUNC(SYSDATE) - 17);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 76', 'Nam', 'Dia chi 76', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 21, TRUNC(SYSDATE) - 21, 305000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 305000, 305000, TRUNC(SYSDATE) - 21);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 77', 'Nam', 'Dia chi 77', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 31, TRUNC(SYSDATE) - 29, TRUNC(SYSDATE) - 29, 138000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 138000, 138000, TRUNC(SYSDATE) - 29);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 78', 'Nam', 'Dia chi 78', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 16, TRUNC(SYSDATE) - 16, 368000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 368000, 368000, TRUNC(SYSDATE) - 16);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 79', 'Nam', 'Dia chi 79', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 22, TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 20, 233000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 233000, 233000, TRUNC(SYSDATE) - 20);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 80', 'Nu', 'Dia chi 80', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 11, TRUNC(SYSDATE) - 9, TRUNC(SYSDATE) - 9, 248000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 248000, 248000, TRUNC(SYSDATE) - 9);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 81', 'Nam', 'Dia chi 81', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 28, TRUNC(SYSDATE) - 28, 492000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 492000, 492000, TRUNC(SYSDATE) - 28);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 82', 'Nu', 'Dia chi 82', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 23, TRUNC(SYSDATE) - 21, TRUNC(SYSDATE) - 21, 232000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 232000, 232000, TRUNC(SYSDATE) - 21);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 83', 'Nu', 'Dia chi 83', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 2, TRUNC(SYSDATE) - 0, TRUNC(SYSDATE) - 0, 344000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 344000, 344000, TRUNC(SYSDATE) - 0);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 84', 'Nam', 'Dia chi 84', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 11, TRUNC(SYSDATE) - 9, TRUNC(SYSDATE) - 9, 126000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 126000, 126000, TRUNC(SYSDATE) - 9);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 85', 'Nu', 'Dia chi 85', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 18, TRUNC(SYSDATE) - 18, 258000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 258000, 258000, TRUNC(SYSDATE) - 18);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 86', 'Nu', 'Dia chi 86', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 5, TRUNC(SYSDATE) - 3, TRUNC(SYSDATE) - 3, 364000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 364000, 364000, TRUNC(SYSDATE) - 3);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 87', 'Nu', 'Dia chi 87', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 32, TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 30, 318000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 318000, 318000, TRUNC(SYSDATE) - 30);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 88', 'Nam', 'Dia chi 88', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 2 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 32, TRUNC(SYSDATE) - 30, TRUNC(SYSDATE) - 30, 393000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 393000, 393000, TRUNC(SYSDATE) - 30);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 89', 'Nu', 'Dia chi 89', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 13, TRUNC(SYSDATE) - 11, TRUNC(SYSDATE) - 11, 251000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 251000, 251000, TRUNC(SYSDATE) - 11);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 90', 'Nu', 'Dia chi 90', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 26, TRUNC(SYSDATE) - 24, TRUNC(SYSDATE) - 24, 120000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 120000, 120000, TRUNC(SYSDATE) - 24);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 91', 'Nu', 'Dia chi 91', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 14, TRUNC(SYSDATE) - 12, TRUNC(SYSDATE) - 12, 403000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 403000, 403000, TRUNC(SYSDATE) - 12);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 92', 'Nu', 'Dia chi 92', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 3 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 22, TRUNC(SYSDATE) - 20, TRUNC(SYSDATE) - 20, 435000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 435000, 435000, TRUNC(SYSDATE) - 20);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 93', 'Nu', 'Dia chi 93', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 15, TRUNC(SYSDATE) - 13, TRUNC(SYSDATE) - 13, 442000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 442000, 442000, TRUNC(SYSDATE) - 13);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 94', 'Nu', 'Dia chi 94', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 10, TRUNC(SYSDATE) - 8, TRUNC(SYSDATE) - 8, 438000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 438000, 438000, TRUNC(SYSDATE) - 8);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 95', 'Nam', 'Dia chi 95', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 3, TRUNC(SYSDATE) - 1, TRUNC(SYSDATE) - 1, 147000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 147000, 147000, TRUNC(SYSDATE) - 1);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 96', 'Nam', 'Dia chi 96', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 4 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 15, TRUNC(SYSDATE) - 13, TRUNC(SYSDATE) - 13, 100000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 100000, 100000, TRUNC(SYSDATE) - 13);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 97', 'Nam', 'Dia chi 97', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 11, TRUNC(SYSDATE) - 9, TRUNC(SYSDATE) - 9, 372000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 372000, 372000, TRUNC(SYSDATE) - 9);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 98', 'Nam', 'Dia chi 98', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 0 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 6, TRUNC(SYSDATE) - 4, TRUNC(SYSDATE) - 4, 169000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 169000, 169000, TRUNC(SYSDATE) - 4);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 99', 'Nu', 'Dia chi 99', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 24, TRUNC(SYSDATE) - 22, TRUNC(SYSDATE) - 22, 400000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 400000, 400000, TRUNC(SYSDATE) - 22);

  INSERT INTO BENHNHAN (TENBENHNHAN, GIOITINH, DIACHI, TINHTRANG_XUATVIEN)
  VALUES ('Benh Nhan 100', 'Nam', 'Dia chi 100', 'Da Xuat Vien');
  INSERT INTO VIENPHI (MABENHNHAN, IDKHOAPHONG, NGAYVAO, NGAYRA, NGAYTHANHTOAN, TONGTIEN)
  VALUES ((SELECT MAX(MABENHNHAN) FROM BENHNHAN), (SELECT MAX(IDKHOAPHONG) - 1 FROM DMKHOAPHONGBV), TRUNC(SYSDATE) - 27, TRUNC(SYSDATE) - 25, TRUNC(SYSDATE) - 25, 495000);
  INSERT INTO VIENPHICT (IDVIENPHI, SOLUONG, DONGIA, SOTIEN, NGAY)
  VALUES ((SELECT MAX(IDVIENPHI) FROM VIENPHI), 1, 495000, 495000, TRUNC(SYSDATE) - 25);

  -- Dynamic updates to simulate realistic BHYT coverage and treatment types
  UPDATE VIENPHICT SET BHYTTRA = CASE WHEN MOD(ID, 3) <> 0 THEN ROUND(SOTIEN * 0.8) ELSE 0 END;

  UPDATE VIENPHI SET LOAI_DIEUTRI = CASE WHEN NGAYRA IS NULL THEN 'NOI_TRU' WHEN MOD(IDVIENPHI, 3) = 0 THEN 'NOI_TRU' ELSE 'NGOAI_TRU' END;
  UPDATE VIENPHI SET NAMQUY = EXTRACT(YEAR FROM NGAYTHANHTOAN) * 10 + TO_NUMBER(TO_CHAR(NGAYTHANHTOAN, 'Q')) WHERE NGAYTHANHTOAN IS NOT NULL;

  -- Update master VIENPHI totals
  UPDATE VIENPHI v SET
    v.TONG_BHYT_TRA = NVL((SELECT SUM(BHYTTRA) FROM VIENPHICT WHERE IDVIENPHI = v.IDVIENPHI), 0) +
                      NVL((SELECT SUM(BHYTTRA) FROM VIENPHICTTHUOC WHERE IDVIENPHI = v.IDVIENPHI), 0);

  UPDATE VIENPHI v SET
    v.TONG_BN_TRA = v.TONGTIEN - v.TONG_BHYT_TRA;

  COMMIT;
END;
/